### ISSUE TITLE
lib: buttons(sibling) should have gap

### ISSUE THREAD

**Issue by 2nthony** [opensquare-network/subsquare#3903]
case:

```css
button + button {
  margin-left: ?px;
}
```

<img width="210" alt="image" src="https://github.com/opensquare-network/subsquare/assets/19513289/589122fe-0dd2-4001-9800-1dcbf6674d39">
