### ISSUE TITLE
Project Westend Res

### ISSUE THREAD

**Issue by Popoulosss** [opensquare-network/subsquare#4237]
Files
[sns-westend.zip](https://github.com/user-attachments/files/15580641/sns-westend.zip)

Color
```css
export const light = {
  dark: false,
  // customized
  // solochain
  // westend
  theme100: "rgba(239,72,106,0.10)",
  theme300: "rgba(239,72,106,0.40)",
  theme500: "rgba(239,72,106,1)",
  navigationBg: "rgba(255,255,255,1)",
  navigationActive: "rgba(246,247,250,1)",
  navigationBorder: "rgba(235,238,244,1)",
};

export const dark = {
  ...light,
  dark: true,
  // customized
  // solochain
  // westend
  theme100: "rgba(239,72,106,0.10)",
  theme300: "rgba(239,72,106,0.40)",
  theme500: "rgba(239,72,106,1)",
  navigationBg: "rgba(33,36,51,1)",
  navigationActive: "rgba(38,41,56,1)",
  navigationBorder: "rgba(39,42,58,1)",
};
``` 

Preview
<img width="640" alt="image" src="https://github.com/opensquare-network/subsquare/assets/59445675/44f5a758-10b6-4008-8192-890bb34166cc">
